# Generated by Django 4.1.3 on 2023-09-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_auto_20211224_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-id']},
        ),
    ]
