# Generated by Django 4.1.3 on 2023-09-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_appointment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='watotoservice',
            name='Address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
