# Generated by Django 4.1.3 on 2023-09-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_watotoservice_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watotoservice',
            name='next_kin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watotoservice',
            name='next_kin_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watotoservice',
            name='opd',
            field=models.CharField(blank=True, choices=[('', 'choice----'), ('OPD', 'OPD')], default='OPD', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watotoservice',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('Children', 'Children'), ('Mzee', 'Mzee'), ('Mjamzito', 'Mjamzito'), ('Wa kawaida', 'Wa kawaida')], default='Children', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watotoservice',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Under Five', 'Under Five'), ('Above 60', 'above 60'), ('Under Five', 'under five'), ('SelfRefferal', 'SelfRefferal'), ('Pregnancy Mother', 'pregnancy mother'), ('Nhif', 'Nhif'), ('Chf', 'Chf')], default='Under Five', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watotoservice',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watotoservice',
            name='residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watotoservice',
            name='service_time',
            field=models.CharField(blank=True, choices=[('', 'choice----'), ('For the First Time', 'For the First Time'), ('Returning', 'Returning')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watotoservice',
            name='sname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watotoservice',
            name='tribe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
