# Generated by Django 4.1.3 on 2023-09-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_alter_watotoservice_next_kin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dozi',
            name='line_eight_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_eight_quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_eight_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_eight_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_five_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_five_quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_five_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_five_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_four_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_four_quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_four_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_four_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_nine_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_nine_quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_nine_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_nine_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_one_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_one_quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_one_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_one_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_seven_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_seven_quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_seven_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_seven_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_six_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_six_quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_six_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_six_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_ten_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_ten_quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_ten_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_ten_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_three_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_three_quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_three_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_three_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_two_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_two_quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_two_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Line Total Price'),
        ),
        migrations.AlterField(
            model_name='dozi',
            name='line_two_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='watotoservice',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'CHOICE GENDER'), ('Male', 'male'), ('Female', 'female')], max_length=100, null=True),
        ),
    ]
